# Generated by Django 3.2.9 on 2022-01-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mensproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensProduct',
        ),
    ]
