# Generated by Django 3.2.9 on 2022-01-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_mensproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('L', 'LARGE'), ('M', 'MEDIUM'), ('S', 'SMALL')], default='L', max_length=1),
        ),
    ]
