# Generated by Django 3.2.9 on 2022-01-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220116_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], default='m', max_length=1),
        ),
    ]
