# Generated by Django 3.2.9 on 2022-01-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_downvote_upvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('L', 'LARGE'), ('M', 'MEDIUM'), ('S', 'SMALL')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('m', 'MALE'), ('f', 'FEMALE')], default='L', max_length=1),
        ),
    ]
