# Generated by Django 3.2.9 on 2022-01-05 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
