# Generated by Django 3.2.9 on 2022-01-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0011_auto_20220105_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
    ]
