# Generated by Django 3.2.9 on 2022-01-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0012_remove_cartitem_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.IntegerField(default=1),
        ),
    ]
