# Generated by Django 3.2.9 on 2022-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
