# Generated by Django 3.2.9 on 2022-01-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cartitem_subtotal'),
        ('order', '0002_remove_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
            preserve_default=False,
        ),
    ]
